In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Ejemplo 1

In [2]:
lista = [31, 28, 29, 19]

Crear una nparray usando la lista anterior

In [3]:
arr = np.array(lista)

In [4]:
arr

array([31, 28, 29, 19])

### Ejemplo 2

In [7]:
lista_2d = [[2,3,4],
            [3,4,5],
            [3,4,5],
            [3,4,5]]

In [8]:
arr = np.array(lista_2d)

In [9]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [10]:
arr.shape

(4, 3)

In [11]:
arr.ndim

2

Mostrar tipo de datos mediante la propieded dtype.

In [12]:
arr.dtype

dtype('int64')

Obtener el tamaño mediante la propiedad size.

In [14]:
arr.size

12

### Ejemplo 3
Crear un nparray de tipo int16.

In [15]:
arr = np.array(lista_2d, dtype=np.int16)

In [16]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]], dtype=int16)

### Ejemplo 4
Llenar un array con ceros.

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Crear matriz con unos.

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Crear matriz sin asignar valores.

In [19]:
np.empty((3,4))

array([[1.65843639e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [6.70380910e-310, 2.25452292e+184, 2.35742957e+184,
        4.32103286e-061],
       [1.35022977e+161, 1.64798296e+185, 7.13037037e-067,
        2.96064288e-032]])

### Ejemplo 5
Crear un array con valores secuenciales.

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Crear un array de 2 dimensiones con la forma 2x5.

In [22]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Ejemplo 6
Crear un array con valores del 10 al 20 incrementando de 2 en 2.

In [23]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### Ejemplo 7
Crear un array con n valores generados en un espacio lineal, para este caso generar 11 valores entre el 10 y el 20.

In [24]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])